server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: prayer-portal-backend
    
  datasource:
    url: jdbc:postgresql://localhost:5432/prayer_portal
    username: ${DB_USERNAME:prayer_user}
    password: ${DB_PASSWORD:prayer_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

logging:
  level:
    com.prayerportal: DEBUG
    org.springframework.security: DEBUG